dosm_clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: default
      host: clickhouse-server
      port: 8123
      user: default
      password: ''
      secure: False
