services:
  clickhouse-server:
    build: clickhouse-server
    ports:
      - "8123:8123"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8123"]

  dbt:
    build: dbt
    entrypoint: dbt
    ports:
      - "8080:8080"
    volumes:
      - ./dbt:/usr/app
    depends_on:
      - clickhouse-server
