version: 2

sources:
  - name: ext_dosm
    schema: ext_dosm
    loader: gcloud storage

    tables:
      - name: cpi_core
        external:
          location: https://storage.googleapis.com/dosm-public-economy/cpi_core.csv
          options:
            format: CSVWithNames
